version: '3' # specify docker-compose version
 
# Define the services/containers to be run
services:
   database: # name of the third service
      image: mongo # specify image to build container from
      ports:
         - "27017:27017"
      #command: "mongo mongodb://database/citartech --eval 'db.pais.drop()'"
   dbseed:
      build: ./dbseed
      depends_on: 
         - database
      links:
         - database
   server: # name of the first service
      build: ./backend # specify the directory of the Dockerfile
      ports:
         - "4000:4000"
      environment:
         - PORT=4000
         - MONGO_URL=mongodb://database/citartech
      depends_on: 
         - database
      links:
         - database


  