version: '3'
 
services:
   database: 
      image: mongo 
      ports:
         - "27017:27017"
   dbseed:
      build: ./dbseed
      depends_on: 
         - database
      links:
         - database
      environment:
         WAIT_HOSTS: database:27017 # Indica qual serviço deve ser esperado
   server: 
      build: ./backend
      ports:
         - "4000:4000"
      environment:
         - PORT=4000
         - MONGO_URL=mongodb://database/citartech
      depends_on: 
         - database
      links:
         - database


  